---

- hosts: localhost

  tasks:
    - name: Instalar GCC 8, 9 y 10
      block:
        - name: Agregar repo ubuntu-toolchain-r
          apt_repository:
            repo: 'ppa:ubuntu-toolchain-r/test'

        - name: Instalar gcc's
          apt:
            name:
              - gcc-8
              - gcc-9
              - gcc-10
            state: latest

    - name: Instalar Clang 10, 11 y 12
      block:
        - name: Agregar llave GPG de LLVM.org
          apt_key: 
            url: https://apt.llvm.org/llvm-snapshot.gpg.key
            state: present

        - name: Agregar repo de clang 11
          apt_repository:
            repo: deb http://apt.llvm.org/{{ansible_distribution_release|lower}}/ llvm-toolchain-{{ansible_distribution_release|lower}}-11 main
            filename: llvm-toolchain-11
            state: present
  
        - name: Agregar repo de clang 12
          apt_repository:
            repo: deb http://apt.llvm.org/{{ansible_distribution_release|lower}}/ llvm-toolchain-{{ansible_distribution_release|lower}}-12 main
            filename: llvm-toolchain-12
            state: present

        - name: Instalar clangs 
          apt:
            name:
              - clang-10
              - clang-11
              - clang-12
            state: latest